# Generated by Django 4.1.7 on 2023-04-13 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="coupon",
            options={
                "ordering": ("code",),
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
            },
        ),
    ]
