# Generated by Django 4.1.7 on 2023-04-08 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_product_created_alter_product_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 8, 11, 14, 27, 427307)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 8, 11, 14, 27, 427307)
            ),
        ),
    ]
