# Generated by Django 4.1.7 on 2023-04-10 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_alter_product_created_alter_product_updated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 10, 18, 18, 38, 540379)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 10, 18, 18, 38, 540379)
            ),
        ),
    ]
