# Generated by Django 4.1.7 on 2023-04-11 10:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0006_alter_product_created_alter_product_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="camera",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="os",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="screen_size",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 13, 29, 52, 358249)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 13, 29, 52, 358249)
            ),
        ),
        migrations.CreateModel(
            name="PhoneConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memory_size", models.CharField(max_length=50)),
                ("RAM_size", models.CharField(default="", max_length=50)),
                (
                    "phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configuration",
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
