# Generated by Django 4.1.7 on 2023-04-11 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_phoneconfiguration_price_alter_product_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="camera",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 14, 10, 5, 447872)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="screen_size",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 14, 10, 5, 447872)
            ),
        ),
    ]
