# Generated by Django 4.1.7 on 2023-04-11 12:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0009_alter_product_camera_alter_product_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product", name="show", field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 15, 8, 25, 559687)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 15, 8, 25, 559687)
            ),
        ),
    ]
