# Generated by Django 4.1.7 on 2023-04-11 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0010_product_show_alter_product_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="show",),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 15, 14, 8, 825885)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 15, 14, 8, 825885)
            ),
        ),
    ]
