# Generated by Django 4.1.7 on 2023-04-11 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_phoneconfiguration_config_alter_product_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 15, 31, 53, 888922)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 15, 31, 53, 888922)
            ),
        ),
    ]
