# Generated by Django 4.1.7 on 2023-04-11 14:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0013_alter_product_created_alter_product_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("slug", models.SlugField(default="slug", max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="productsss/")),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phones",
                        to="shop.category",
                    ),
                ),
                (
                    "main_configuration",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_phone",
                        to="shop.phoneconfiguration",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 17, 58, 5, 479708)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 17, 58, 5, 479708)
            ),
        ),
        migrations.CreateModel(
            name="PhoneConfigurations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("screen_size", models.FloatField()),
                ("memory_size", models.PositiveIntegerField()),
                ("camera", models.CharField(max_length=255)),
                ("os", models.CharField(max_length=255)),
                (
                    "phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="configurations",
                        to="shop.phone",
                    ),
                ),
            ],
        ),
    ]
