# Generated by Django 4.1.7 on 2023-04-11 15:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_phone_alter_product_created_alter_product_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="main_configuration",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_phone",
                to="shop.phoneconfigurations",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 18, 0, 38, 324885)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 18, 0, 38, 324885)
            ),
        ),
    ]
