# Generated by Django 4.1.7 on 2023-04-11 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0017_remove_phoneconfiguration_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="phoneconfiguration",
            name="config_id",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 18, 46, 29, 129810)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 18, 46, 29, 129810)
            ),
        ),
    ]
