# Generated by Django 4.1.7 on 2023-04-11 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_phoneconfiguration_config_id_alter_product_created_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="phoneconfiguration", name="RAM_size",),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 19, 2, 25, 855521)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 11, 19, 2, 25, 855521)
            ),
        ),
    ]
