# Generated by Django 4.1.7 on 2023-04-12 08:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_remove_phoneconfiguration_ram_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 11, 43, 18, 922031)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 11, 43, 18, 922031)
            ),
        ),
        migrations.CreateModel(
            name="PhoneCfg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cfg", models.ManyToManyField(to="shop.product")),
                (
                    "phone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cfg",
                        to="shop.product",
                    ),
                ),
            ],
        ),
    ]
