# Generated by Django 4.1.7 on 2023-04-12 09:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0020_alter_product_created_alter_product_updated_phonecfg"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneColors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="phoneconfiguration", old_name="phone", new_name="phone_id",
        ),
        migrations.RemoveField(model_name="phoneconfiguration", name="config_id",),
        migrations.RemoveField(model_name="phoneconfiguration", name="config_slug",),
        migrations.RemoveField(model_name="phoneconfiguration", name="memory_size",),
        migrations.RemoveField(model_name="phoneconfiguration", name="price",),
        migrations.AddField(
            model_name="phoneconfiguration",
            name="phone_configurations",
            field=models.ManyToManyField(
                related_name="Configurations", to="shop.product"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="memory",
            field=models.CharField(default="0GB", max_length=10),
        ),
        migrations.AddField(
            model_name="product",
            name="ram",
            field=models.CharField(default="0GB", max_length=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 12, 5, 55, 678833)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 12, 5, 55, 678833)
            ),
        ),
        migrations.DeleteModel(name="PhoneCfg",),
        migrations.AddField(
            model_name="phonecolors",
            name="phone_colors",
            field=models.ManyToManyField(related_name="Colors", to="shop.product"),
        ),
        migrations.AddField(
            model_name="phonecolors",
            name="phone_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="color",
                to="shop.product",
            ),
        ),
    ]
