# Generated by Django 4.1.7 on 2023-04-12 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0021_phonecolors_rename_phone_phoneconfiguration_phone_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ph_color",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 12, 25, 44, 300296)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 12, 25, 44, 300296)
            ),
        ),
    ]
