# Generated by Django 4.1.7 on 2023-04-12 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0022_product_ph_color_alter_product_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="camera",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 12, 35, 9, 43346)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 12, 35, 9, 43346)
            ),
        ),
    ]
