# Generated by Django 4.1.7 on 2023-04-12 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0023_alter_product_camera_alter_product_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="ph_color", new_name="ph_color_hex",
        ),
        migrations.AddField(
            model_name="product",
            name="ph_color_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 21, 8, 6, 193820)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 21, 8, 6, 193820)
            ),
        ),
    ]
