# Generated by Django 4.1.7 on 2023-04-12 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0024_rename_ph_color_product_ph_color_hex_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhoneDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(default="", max_length=100)),
                ("display", models.TextField()),
                ("processor", models.TextField()),
                ("size_and_weight", models.TextField()),
                ("camera", models.TextField()),
                ("video", models.TextField()),
                ("front_cam", models.TextField()),
                ("mobile_cnct", models.TextField()),
                ("os", models.CharField(default="", max_length=25)),
            ],
        ),
        migrations.RemoveField(model_name="product", name="camera",),
        migrations.RemoveField(model_name="product", name="os",),
        migrations.RemoveField(model_name="product", name="screen_size",),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 21, 35, 57, 889680)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 21, 35, 57, 889680)
            ),
        ),
    ]
