# Generated by Django 4.1.7 on 2023-04-12 18:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0025_phonedetails_remove_product_camera_remove_product_os_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="details",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop.phonedetails",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 21, 44, 24, 279739)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 12, 21, 44, 24, 279739)
            ),
        ),
    ]
