# Generated by Django 4.1.7 on 2023-04-13 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0027_alter_phonecolors_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 13, 23, 37, 27, 569241)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 13, 23, 37, 27, 569241)
            ),
        ),
    ]
