# Generated by Django 4.1.7 on 2023-04-14 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0028_alter_product_created_alter_product_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="ph_color_name_en",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AddField(
            model_name="product",
            name="ph_color_name_ru",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 14, 9, 41, 11, 408569)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 14, 9, 41, 11, 408569)
            ),
        ),
    ]
