# Generated by Django 4.1.7 on 2023-04-14 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0031_alter_product_created_alter_product_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="phonedetails",
            name="camera_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="phonedetails",
            name="camera_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="phonedetails",
            name="display_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="phonedetails",
            name="display_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="phonedetails",
            name="front_cam_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="phonedetails",
            name="front_cam_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="phonedetails",
            name="mobile_cnct_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="phonedetails",
            name="mobile_cnct_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="phonedetails",
            name="processor_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="phonedetails",
            name="processor_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="phonedetails",
            name="size_and_weight_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="phonedetails",
            name="size_and_weight_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="phonedetails",
            name="video_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="phonedetails",
            name="video_ru",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="created",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 14, 9, 57, 0, 426722)
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 14, 9, 57, 0, 426722)
            ),
        ),
    ]
